
/**
 * Returns a unique identifier for the security rule entry.
 * Can be used
 * @param {object} entry the security rule entry
 * @returns {string} a unique identifier for a security entry (that is not the ID but the type-entry couple)
 */
export function getEntryIdKey(entry) {
    if (!entry) return '';
    return `${entry.type ?? 'entry'}-${entry.name ?? ''}`;
}
/**
 * Returns the security rule corresponding unique identifier generated by `getEntryIdKey`.
 * to find match between security rules associated with a particular group and the group.
 * @param {object} group returns a unique identifier that can be used to find if  a security rule entry
 * @returns {string} a unique identifier
 */
export function getGroupIdKey(group) {
    if (!group) return '';
    return `group-${group.groupName}`;
}
