FROM mapstore-base:latest

ENV CATALINA_BASE="/usr/local/tomcat"
ARG MAPSTORE_WEBAPP_SRC="./web/target/mapstore.war"
ARG UID=1001
ARG GID=1001
ARG UNAME=tomcat

COPY ${MAPSTORE_WEBAPP_SRC} ${CATALINA_BASE}/webapps/mapstore.war

USER root
RUN chown $UID:$GID ${CATALINA_BASE}/webapps/mapstore.war
USER $UNAME

WORKDIR ${CATALINA_BASE}
